### ISSUE TITLE
报这个错误怎么解决，求大佬！！

### ISSUE THREAD

**Issue by songguowei** [wangshub/Douyin-Bot#109]
PS E:\python\Douyin-Bot-master> python douyin-bot.py
检查设备是否连接...
Traceback (most recent call last):
  File "douyin-bot.py", line 33, in <module>
    adb.test_device()
  File "E:\python\Douyin-Bot-master\common\auto_adb.py", line 49, in test_device
    if output[0].decode('utf8') == 'List of devices attached\n\n':
AttributeError: 'str' object has no attribute 'decode'
PS E:\python\Douyin-Bot-master>

**Comment by wank1r** [comment]
adb配置好了吗
